name: Publish Python  distributions to PyPI and TestPyPI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Twine
      run: |
        pip install twine==1.11.0
    - name: Build Release Wheel
      run: |
        ./build.sh release
    - name: Publish package to PyPi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
