name: Test- Provision a device

env:
  FILEPATH: .github/workflows/exo_tests.py
  
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Provision a device, check for config_io, and write data  to Murano after a new Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Requests
      run: |
        pip install requests
    - name: Provision Device, check for config, and write data  to Murano
      run: |
        python $FILEPATH
