name: Test- Provision a device
  
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Provision a device to Murano after a new Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requests
      run: pip install requests
      shell: bash
    - name: Provision Device to Murano
      run: python .github/workflows/provision.py
      shell: bash
